# Generated by Django 3.0.6 on 2020-05-05 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmaker', '0003_auto_20200505_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
