# Generated by Django 3.0.6 on 2020-05-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmaker', '0004_game_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='players',
            field=models.ManyToManyField(to='bookmaker.Player'),
        ),
    ]
